// Node smoke test: load migrated legacy data into a MemoryRepository and exercise feature modules.
import { readFileSync } from 'node:fs';
import { MemoryRepository } from '../js/storage/repository.js';
import { state, loadAll, replaceAll } from '../js/core/state.js';
import { parseBackupText } from '../js/storage/backup.js';
import { evaluateStreak } from '../js/features/streaks.js';
import { summary, plannedVsActual, focusByProject, heatmapData, dailyPlanVsActual } from '../js/features/analytics.js';
import { ensureOccurrences, createTask, completeTask, moveTask, tasksOn, dayStatus } from '../js/features/tasks.js';
import { setDayWin, dayWinStatus, workload } from '../js/features/daily-plan.js';
import { planInsights } from '../js/features/insights.js';
import { dayReview } from '../js/features/review.js';
import { monthData } from '../js/features/calendar.js';
import { todayKey, addDays } from '../js/utils/dates.js';

let failures = 0;
const ok = (c, m) => { console.log(`${c ? 'PASS' : 'FAIL'}  ${m}`); if (!c) failures++; };
const repo = new MemoryRepository();
await loadAll(repo);
const parsed = parseBackupText(readFileSync((process.argv[2] || process.env.POMO_LEGACY || 'pomofocus-2026-09-30.json'), 'utf8'));
ok(parsed.ok, 'legacy file parses via backup pipeline');
await replaceAll(parsed.dataset);
const s = evaluateStreak('lg_streak_focus', '2026-10-01');
ok(s.current === 6, `Daily focus streak on Oct 1 = 6 (v1 streak 6) → ${s.current} (longest ${s.longest})`);
const all = summary('2020-01-01', '2026-12-31');
ok(all.pomos === 546 && Math.round(all.focusMin) === 16145, `summary totals ${all.pomos} / ${Math.round(all.focusMin)}`);
const fp = focusByProject('2020-01-01', '2026-12-31');
ok(fp.reduce((a, b) => a + b.pomos, 0) === 546, 'focus by project sums to 546');
const pva = plannedVsActual({});
console.log('pva reliable rows', pva.count, 'excluded', pva.excludedUnreliable, 'ratio', pva.ratio.toFixed(2));
ok(pva.excludedUnreliable > 0, 'unreliable legacy estimates excluded by default');
const hm = heatmapData('2026-01-01', '2026-12-31');
ok(hm.days.length === 365, 'heatmap 365 days');
const today = todayKey();
await ensureOccurrences(today);
const occ = tasksOn(today);
console.log('occurrences today', occ.map((t) => t.title));
ok(occ.length >= 3, 'daily recurring occurrences generated for today');
await ensureOccurrences(today);
ok(tasksOn(today).length === occ.length, 'ensureOccurrences idempotent');
const t = await createTask({ title: 'Write report', estimate: 3, plannedDate: today, priority: 'high' });
await setDayWin(today, t.id);
ok(dayWinStatus(today).key === 'open', 'day win open');
let threw = false; try { const t2 = await createTask({ title: 'x', plannedDate: addDays(today, 1) }); await setDayWin(today, t2.id); } catch { threw = true; }
ok(threw, 'cannot set Day Win to task from another day');
await moveTask(t.id, addDays(today, 1));
ok(dayStatus(t, today).key === 'moved' || dayStatus(state.tasks.get(t.id), today).key === 'moved', 'moved task shows as moved on original day');
ok(dayWinStatus(today).key === 'moved', 'Day Win status moved (neutral)');
await moveTask(t.id, today);
await completeTask(t.id);
ok(dayWinStatus(today).key === 'completed', 'Day Win completed');
console.log('workload', workload(today).level, 'insights', planInsights(today).map((i) => i.id));
const r = dayReview('2026-09-30');
ok(r.focus.pomos > 0, `review Sep 30 pomos ${r.focus.pomos}`);
const md = monthData(2026, 8);
ok(md.length === 42, 'month grid 42 cells');
ok(dailyPlanVsActual('2026-09-01', '2026-09-30').length === 30, 'daily plan vs actual');
console.log(failures ? `${failures} FAILED` : 'ALL PASS');
process.exit(failures ? 1 : 0);
